### ISSUE TITLE
Keynote file type

### ISSUE THREAD

**Issue by davidxcrowe** [zone117x/MimeMapping#13]
Apple Keynote files (.key, application/vnd.apple.keynote) isn't listed. Do you not refer to https://www.iana.org/assignments/media-types/media-types.xhtml ?

D

**Comment by davidxcrowe** [comment]
Sorry, not thinking well today. However, how do we handle things like .key files?

**Comment by zone117x** [comment]
Yes, IANA entries are retrieved via http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types

Looks like that list hasn't been updated since the `application/vnd.apple.keynote` type was registered.

The generator https://github.com/zone117x/MimeMapping/blob/master/KnownMimeTypes.tt could be refactored to pull from the full https://github.com/jshttp/mime-db dataset which is more up to date. 

PRs welcome!

**Comment by viceice** [comment]
Do you refer to this file?
https://github.com/jshttp/mime-db/blob/master/db.json

maybe simply switch from `src/custom-types.json` to `db.json` ?
